apiVersion: v1
kind: Service
metadata:
  name: oracledb-rac-node1-svc
  namespace: oraclerac
spec:
  selector:
    app: oracledb-rac-node1
  clusterIP: None
  ports:
    - protocol: TCP
      port: 1521
      targetPort: 1521

---

apiVersion: v1
kind: Service
metadata:
  name: oracledb-rac-node2-svc
  namespace: oraclerac
spec:
  selector:
    app: oracledb-rac-node2
  clusterIP: None
  ports:
    - protocol: TCP
      port: 1521
      targetPort: 1521